language: c

sudo: required

matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

env:
  - CABALVER=1.16 GHCVER=7.6.3
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.3
  - CABALVER=1.24 GHCVER=8.0.1
  - CABALVER=head GHCVER=head

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libgtk2.0-dev libnotify-dev
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal update
  - cabal install alex
  - cabal install happy
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests libnotify.cabal

script:
  - cabal install --enable-tests libnotify.cabal
  - cabal sdist && cabal install --enable-tests dist/libnotify-*.tar.gz
